--
-- PostgreSQL database dump
--

-- Dumped from database version 11.2
-- Dumped by pg_dump version 12.0

-- Started on 2020-01-22 21:07:48

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

--
-- TOC entry 216 (class 1259 OID 28951)
-- Name: activation_code; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.activation_code (
                                        id bigint NOT NULL,
                                        code character varying(255) NOT NULL,
                                        creation_date timestamp without time zone,
                                        user_id bigint
);


ALTER TABLE public.activation_code OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 28949)
-- Name: activation_code_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.activation_code ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.activation_code_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );


--
-- TOC entry 207 (class 1259 OID 28354)
-- Name: answers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.answers (
                                id bigint NOT NULL,
                                text text,
                                questionnaire_id bigint NOT NULL,
                                question_id bigint NOT NULL,
                                text_list text
);


ALTER TABLE public.answers OWNER TO postgres;

--
-- TOC entry 206 (class 1259 OID 28352)
-- Name: answers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.answers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.answers_id_seq OWNER TO postgres;

--
-- TOC entry 2947 (class 0 OID 0)
-- Dependencies: 206
-- Name: answers_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.answers_id_seq OWNED BY public.answers.id;


--
-- TOC entry 209 (class 1259 OID 28375)
-- Name: diagnoses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.diagnoses (
                                  id bigint NOT NULL,
                                  text text NOT NULL
);


ALTER TABLE public.diagnoses OWNER TO postgres;

--
-- TOC entry 208 (class 1259 OID 28373)
-- Name: diagnoses_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.diagnoses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.diagnoses_id_seq OWNER TO postgres;

--
-- TOC entry 2948 (class 0 OID 0)
-- Dependencies: 208
-- Name: diagnoses_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.diagnoses_id_seq OWNED BY public.diagnoses.id;


--
-- TOC entry 211 (class 1259 OID 28391)
-- Name: doctors; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.doctors (
                                id bigint NOT NULL,
                                user_id bigint NOT NULL,
                                description text
);


ALTER TABLE public.doctors OWNER TO postgres;

--
-- TOC entry 210 (class 1259 OID 28389)
-- Name: doctors_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.doctors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.doctors_id_seq OWNER TO postgres;

--
-- TOC entry 2949 (class 0 OID 0)
-- Dependencies: 210
-- Name: doctors_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.doctors_id_seq OWNED BY public.doctors.id;


--
-- TOC entry 214 (class 1259 OID 28413)
-- Name: doctors_patients; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.doctors_patients (
                                         doctor_id bigint NOT NULL,
                                         patient_id bigint NOT NULL
);


ALTER TABLE public.doctors_patients OWNER TO postgres;

--
-- TOC entry 196 (class 1259 OID 17651)
-- Name: hibernate_sequence; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.hibernate_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.hibernate_sequence OWNER TO postgres;

--
-- TOC entry 213 (class 1259 OID 28402)
-- Name: patients; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.patients (
                                 id bigint NOT NULL,
                                 diagnosis_id bigint,
                                 user_id bigint NOT NULL
);


ALTER TABLE public.patients OWNER TO postgres;

--
-- TOC entry 212 (class 1259 OID 28400)
-- Name: patients_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.patients_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.patients_id_seq OWNER TO postgres;

--
-- TOC entry 2950 (class 0 OID 0)
-- Dependencies: 212
-- Name: patients_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.patients_id_seq OWNED BY public.patients.id;


--
-- TOC entry 218 (class 1259 OID 29008)
-- Name: questionnaire_types; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.questionnaire_types (
                                            id bigint NOT NULL,
                                            type text NOT NULL,
                                            description text
);


ALTER TABLE public.questionnaire_types OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 29006)
-- Name: questionnaire_types_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.questionnaire_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.questionnaire_types_id_seq OWNER TO postgres;

--
-- TOC entry 2951 (class 0 OID 0)
-- Dependencies: 217
-- Name: questionnaire_types_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.questionnaire_types_id_seq OWNED BY public.questionnaire_types.id;


--
-- TOC entry 205 (class 1259 OID 28343)
-- Name: questionnaires; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.questionnaires (
                                       id bigint NOT NULL,
                                       user_id bigint NOT NULL,
                                       date timestamp with time zone NOT NULL,
                                       processed boolean DEFAULT false NOT NULL,
                                       diagnosis_id bigint,
                                       type_id bigint
);


ALTER TABLE public.questionnaires OWNER TO postgres;

--
-- TOC entry 204 (class 1259 OID 28341)
-- Name: questionnaires_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.questionnaires_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.questionnaires_id_seq OWNER TO postgres;

--
-- TOC entry 2952 (class 0 OID 0)
-- Dependencies: 204
-- Name: questionnaires_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.questionnaires_id_seq OWNED BY public.questionnaires.id;


--
-- TOC entry 221 (class 1259 OID 29026)
-- Name: questionnaires_questions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.questionnaires_questions (
                                                 type_id bigint NOT NULL,
                                                 question_id bigint NOT NULL,
                                                 question_order integer NOT NULL
);


ALTER TABLE public.questionnaires_questions OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 29024)
-- Name: questionnaires_questions_question_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.questionnaires_questions_question_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.questionnaires_questions_question_id_seq OWNER TO postgres;

--
-- TOC entry 2953 (class 0 OID 0)
-- Dependencies: 220
-- Name: questionnaires_questions_question_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.questionnaires_questions_question_id_seq OWNED BY public.questionnaires_questions.question_id;


--
-- TOC entry 219 (class 1259 OID 29022)
-- Name: questionnaires_questions_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.questionnaires_questions_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.questionnaires_questions_type_id_seq OWNER TO postgres;

--
-- TOC entry 2954 (class 0 OID 0)
-- Dependencies: 219
-- Name: questionnaires_questions_type_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.questionnaires_questions_type_id_seq OWNED BY public.questionnaires_questions.type_id;


--
-- TOC entry 203 (class 1259 OID 28332)
-- Name: questions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.questions (
                                  id bigint NOT NULL,
                                  text text NOT NULL,
                                  options text,
                                  description text,
                                  input_type text NOT NULL,
                                  answer_type text,
                                  category character varying(255),
                                  depends_on_the_question_id bigint
);


ALTER TABLE public.questions OWNER TO postgres;

--
-- TOC entry 202 (class 1259 OID 28330)
-- Name: questions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.questions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.questions_id_seq OWNER TO postgres;

--
-- TOC entry 2955 (class 0 OID 0)
-- Dependencies: 202
-- Name: questions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.questions_id_seq OWNED BY public.questions.id;


--
-- TOC entry 200 (class 1259 OID 28306)
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
                              id bigint NOT NULL,
                              rolename text NOT NULL
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- TOC entry 199 (class 1259 OID 28304)
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.roles_id_seq OWNER TO postgres;

--
-- TOC entry 2956 (class 0 OID 0)
-- Dependencies: 199
-- Name: roles_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.roles_id_seq OWNED BY public.roles.id;


--
-- TOC entry 198 (class 1259 OID 28294)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
                              id bigint NOT NULL,
                              email text NOT NULL,
                              password text NOT NULL,
                              first_name text NOT NULL,
                              activated boolean DEFAULT false NOT NULL,
                              phone_number text,
                              registration_date timestamp with time zone NOT NULL,
                              gender text NOT NULL,
                              second_name text,
                              last_visit_date timestamp with time zone
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 197 (class 1259 OID 28292)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.users_id_seq OWNER TO postgres;

--
-- TOC entry 2957 (class 0 OID 0)
-- Dependencies: 197
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- TOC entry 201 (class 1259 OID 28315)
-- Name: users_roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_roles (
                                    user_id bigint NOT NULL,
                                    role_id bigint NOT NULL
);


ALTER TABLE public.users_roles OWNER TO postgres;

--
-- TOC entry 2771 (class 2604 OID 28357)
-- Name: answers id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.answers ALTER COLUMN id SET DEFAULT nextval('public.answers_id_seq'::regclass);


--
-- TOC entry 2772 (class 2604 OID 28378)
-- Name: diagnoses id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.diagnoses ALTER COLUMN id SET DEFAULT nextval('public.diagnoses_id_seq'::regclass);


--
-- TOC entry 2773 (class 2604 OID 28394)
-- Name: doctors id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.doctors ALTER COLUMN id SET DEFAULT nextval('public.doctors_id_seq'::regclass);


--
-- TOC entry 2774 (class 2604 OID 28405)
-- Name: patients id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.patients ALTER COLUMN id SET DEFAULT nextval('public.patients_id_seq'::regclass);


--
-- TOC entry 2775 (class 2604 OID 29011)
-- Name: questionnaire_types id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire_types ALTER COLUMN id SET DEFAULT nextval('public.questionnaire_types_id_seq'::regclass);


--
-- TOC entry 2769 (class 2604 OID 28346)
-- Name: questionnaires id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaires ALTER COLUMN id SET DEFAULT nextval('public.questionnaires_id_seq'::regclass);


--
-- TOC entry 2776 (class 2604 OID 29029)
-- Name: questionnaires_questions type_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaires_questions ALTER COLUMN type_id SET DEFAULT nextval('public.questionnaires_questions_type_id_seq'::regclass);


--
-- TOC entry 2777 (class 2604 OID 29030)
-- Name: questionnaires_questions question_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaires_questions ALTER COLUMN question_id SET DEFAULT nextval('public.questionnaires_questions_question_id_seq'::regclass);


--
-- TOC entry 2768 (class 2604 OID 28335)
-- Name: questions id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questions ALTER COLUMN id SET DEFAULT nextval('public.questions_id_seq'::regclass);


--
-- TOC entry 2767 (class 2604 OID 28309)
-- Name: roles id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles ALTER COLUMN id SET DEFAULT nextval('public.roles_id_seq'::regclass);


--
-- TOC entry 2765 (class 2604 OID 28297)
-- Name: users id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- TOC entry 2800 (class 2606 OID 28955)
-- Name: activation_code activation_code_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.activation_code
    ADD CONSTRAINT activation_code_pkey PRIMARY KEY (id);


--
-- TOC entry 2790 (class 2606 OID 28362)
-- Name: answers answers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.answers
    ADD CONSTRAINT answers_pkey PRIMARY KEY (id);


--
-- TOC entry 2792 (class 2606 OID 28383)
-- Name: diagnoses diagnoses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.diagnoses
    ADD CONSTRAINT diagnoses_pkey PRIMARY KEY (id);


--
-- TOC entry 2798 (class 2606 OID 28417)
-- Name: doctors_patients doctors_patients_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.doctors_patients
    ADD CONSTRAINT doctors_patients_pkey PRIMARY KEY (doctor_id, patient_id);


--
-- TOC entry 2794 (class 2606 OID 28399)
-- Name: doctors doctors_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.doctors
    ADD CONSTRAINT doctors_pkey PRIMARY KEY (id);


--
-- TOC entry 2796 (class 2606 OID 28407)
-- Name: patients patients_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.patients
    ADD CONSTRAINT patients_pkey PRIMARY KEY (id);


--
-- TOC entry 2802 (class 2606 OID 29016)
-- Name: questionnaire_types questionnaire_types_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaire_types
    ADD CONSTRAINT questionnaire_types_pkey PRIMARY KEY (id);


--
-- TOC entry 2788 (class 2606 OID 28351)
-- Name: questionnaires questionnaires_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaires
    ADD CONSTRAINT questionnaires_pkey PRIMARY KEY (id);


--
-- TOC entry 2804 (class 2606 OID 29032)
-- Name: questionnaires_questions questionnaires_questions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaires_questions
    ADD CONSTRAINT questionnaires_questions_pkey PRIMARY KEY (question_id, type_id);


--
-- TOC entry 2786 (class 2606 OID 28340)
-- Name: questions questions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_pkey PRIMARY KEY (id);


--
-- TOC entry 2782 (class 2606 OID 28314)
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- TOC entry 2780 (class 2606 OID 28299)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 2784 (class 2606 OID 28319)
-- Name: users_roles users_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_roles
    ADD CONSTRAINT users_roles_pkey PRIMARY KEY (user_id, role_id);


--
-- TOC entry 2778 (class 1259 OID 28961)
-- Name: users_email_uindex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX users_email_uindex ON public.users USING btree (email);


--
-- TOC entry 2812 (class 2606 OID 28368)
-- Name: answers answers_to_questions; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.answers
    ADD CONSTRAINT answers_to_questions FOREIGN KEY (question_id) REFERENCES public.questions(id) ON DELETE CASCADE;


--
-- TOC entry 2811 (class 2606 OID 28363)
-- Name: answers answers_to_qustionnaires; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.answers
    ADD CONSTRAINT answers_to_qustionnaires FOREIGN KEY (questionnaire_id) REFERENCES public.questionnaires(id) ON DELETE CASCADE;


--
-- TOC entry 2816 (class 2606 OID 28418)
-- Name: doctors_patients doctors_patients_to_doctors; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.doctors_patients
    ADD CONSTRAINT doctors_patients_to_doctors FOREIGN KEY (doctor_id) REFERENCES public.doctors(id) ON DELETE CASCADE;


--
-- TOC entry 2817 (class 2606 OID 28423)
-- Name: doctors_patients doctors_patients_to_patients; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.doctors_patients
    ADD CONSTRAINT doctors_patients_to_patients FOREIGN KEY (patient_id) REFERENCES public.patients(id) ON DELETE CASCADE;


--
-- TOC entry 2813 (class 2606 OID 28989)
-- Name: doctors doctors_to_users; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.doctors
    ADD CONSTRAINT doctors_to_users FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- TOC entry 2807 (class 2606 OID 29001)
-- Name: questions fklpkpm87ucr1aqr0f3b22avp53; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT fklpkpm87ucr1aqr0f3b22avp53 FOREIGN KEY (depends_on_the_question_id) REFERENCES public.questions(id);


--
-- TOC entry 2818 (class 2606 OID 28962)
-- Name: activation_code fktd7d6vtl8waqkulk2wlkpaqhe; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.activation_code
    ADD CONSTRAINT fktd7d6vtl8waqkulk2wlkpaqhe FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- TOC entry 2814 (class 2606 OID 28408)
-- Name: patients patients_to_diagnoses; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.patients
    ADD CONSTRAINT patients_to_diagnoses FOREIGN KEY (diagnosis_id) REFERENCES public.diagnoses(id) ON DELETE SET NULL;


--
-- TOC entry 2815 (class 2606 OID 28994)
-- Name: patients patpatients_to_usrers; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.patients
    ADD CONSTRAINT patpatients_to_usrers FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- TOC entry 2808 (class 2606 OID 28384)
-- Name: questionnaires questionnaires_to_diagnosis; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaires
    ADD CONSTRAINT questionnaires_to_diagnosis FOREIGN KEY (diagnosis_id) REFERENCES public.diagnoses(id) ON DELETE SET NULL;


--
-- TOC entry 2810 (class 2606 OID 29017)
-- Name: questionnaires questionnaires_to_types; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaires
    ADD CONSTRAINT questionnaires_to_types FOREIGN KEY (type_id) REFERENCES public.questionnaire_types(id) NOT VALID;


--
-- TOC entry 2809 (class 2606 OID 28497)
-- Name: questionnaires questionnaires_to_users; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaires
    ADD CONSTRAINT questionnaires_to_users FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- TOC entry 2820 (class 2606 OID 29038)
-- Name: questionnaires_questions to_question; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaires_questions
    ADD CONSTRAINT to_question FOREIGN KEY (question_id) REFERENCES public.questions(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- TOC entry 2819 (class 2606 OID 29033)
-- Name: questionnaires_questions to_type; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questionnaires_questions
    ADD CONSTRAINT to_type FOREIGN KEY (type_id) REFERENCES public.questionnaire_types(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- TOC entry 2806 (class 2606 OID 28325)
-- Name: users_roles users_roles_to_roles; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_roles
    ADD CONSTRAINT users_roles_to_roles FOREIGN KEY (role_id) REFERENCES public.roles(id) ON DELETE CASCADE;


--
-- TOC entry 2805 (class 2606 OID 28320)
-- Name: users_roles users_roles_to_users; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_roles
    ADD CONSTRAINT users_roles_to_users FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
